"""Autogenerate after table already exists

Revision ID: 07e34a07cb00
Revises: 
Create Date: 2025-04-06 17:47:16.169904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e34a07cb00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanban_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanban_card', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
